In [97]:
import pandas as pd
import numpy as np

In [98]:
df_raw = pd.read_csv("../data/raw/datas.csv", encoding="utf-8-sig")
df_clean = df_raw[
    (df_raw["region"] != "ทั่วประเทศ") & (df_raw["size_estabish"] != "รวม")
].copy()
df_clean.columns = df_clean.columns.str.strip()
df_clean

,year,region,size_estabish,value,unit,source
45,2542,กรุงเทพมหานคร,ต่ำกว่า 60 ห้อง,297061.7,พันบาท,สำนักงานสถิติแห่งชาติ
46,2544,กรุงเทพมหานคร,ต่ำกว่า 60 ห้อง,316149.6,พันบาท,สำนักงานสถิติแห่งชาติ
47,2546,กรุงเทพมหานคร,ต่ำกว่า 60 ห้อง,292475.0,พันบาท,สำนักงานสถิติแห่งชาติ
48,2548,กรุงเทพมหานคร,ต่ำกว่า 60 ห้อง,318711.4,พันบาท,สำนักงานสถิติแห่งชาติ
49,2550,กรุงเทพมหานคร,ต่ำกว่า 60 ห้อง,443951.1,พันบาท,สำนักงานสถิติแห่งชาติ
...,...,...,...,...,...,...
211,2550,ภาคใต้,150 ห้องขึ้นไป,9014235.0,พันบาท,สำนักงานสถิติแห่งชาติ
212,2552,ภาคใต้,150 ห้องขึ้นไป,23667391.4,พันบาท,สำนักงานสถิติแห่งชาติ
213,2554,ภาคใต้,150 ห้องขึ้นไป,18832569.3,พันบาท,สำนักงานสถิติแห่งชาติ
214,2556,ภาคใต้,150 ห้องขึ้นไป,44307960.0,พันบาท,สำนักงานสถิติแห่งชาติ
215,2558,ภาคใต้,150 ห้องขึ้นไป,30561545.7,พันบาท,สำนักงานสถิติแห่งชาติ

In [99]:
region_map = {
    "กรุงเทพมหานคร": "Bangkok",
    "ภาคกลาง": "Central",
    "ภาคเหนือ": "Northern",
    "ภาคตะวันออกเฉียงเหนือ": "Northeastern",
    "ภาคใต้": "Southern",
}
df_clean["region"] = df_clean["region"].map(region_map)
df_clean

,year,region,size_estabish,value,unit,source
45,2542,Bangkok,ต่ำกว่า 60 ห้อง,297061.7,พันบาท,สำนักงานสถิติแห่งชาติ
46,2544,Bangkok,ต่ำกว่า 60 ห้อง,316149.6,พันบาท,สำนักงานสถิติแห่งชาติ
47,2546,Bangkok,ต่ำกว่า 60 ห้อง,292475.0,พันบาท,สำนักงานสถิติแห่งชาติ
48,2548,Bangkok,ต่ำกว่า 60 ห้อง,318711.4,พันบาท,สำนักงานสถิติแห่งชาติ
49,2550,Bangkok,ต่ำกว่า 60 ห้อง,443951.1,พันบาท,สำนักงานสถิติแห่งชาติ
...,...,...,...,...,...,...
211,2550,Southern,150 ห้องขึ้นไป,9014235.0,พันบาท,สำนักงานสถิติแห่งชาติ
212,2552,Southern,150 ห้องขึ้นไป,23667391.4,พันบาท,สำนักงานสถิติแห่งชาติ
213,2554,Southern,150 ห้องขึ้นไป,18832569.3,พันบาท,สำนักงานสถิติแห่งชาติ
214,2556,Southern,150 ห้องขึ้นไป,44307960.0,พันบาท,สำนักงานสถิติแห่งชาติ
215,2558,Southern,150 ห้องขึ้นไป,30561545.7,พันบาท,สำนักงานสถิติแห่งชาติ

In [100]:
df_clean["value"] = df_clean["value"] * 1000
df_clean

,year,region,size_estabish,value,unit,source
45,2542,Bangkok,ต่ำกว่า 60 ห้อง,2.970617e+08,พันบาท,สำนักงานสถิติแห่งชาติ
46,2544,Bangkok,ต่ำกว่า 60 ห้อง,3.161496e+08,พันบาท,สำนักงานสถิติแห่งชาติ
47,2546,Bangkok,ต่ำกว่า 60 ห้อง,2.924750e+08,พันบาท,สำนักงานสถิติแห่งชาติ
48,2548,Bangkok,ต่ำกว่า 60 ห้อง,3.187114e+08,พันบาท,สำนักงานสถิติแห่งชาติ
49,2550,Bangkok,ต่ำกว่า 60 ห้อง,4.439511e+08,พันบาท,สำนักงานสถิติแห่งชาติ
...,...,...,...,...,...,...
211,2550,Southern,150 ห้องขึ้นไป,9.014235e+09,พันบาท,สำนักงานสถิติแห่งชาติ
212,2552,Southern,150 ห้องขึ้นไป,2.366739e+10,พันบาท,สำนักงานสถิติแห่งชาติ
213,2554,Southern,150 ห้องขึ้นไป,1.883257e+10,พันบาท,สำนักงานสถิติแห่งชาติ
214,2556,Southern,150 ห้องขึ้นไป,4.430796e+10,พันบาท,สำนักงานสถิติแห่งชาติ
215,2558,Southern,150 ห้องขึ้นไป,3.056155e+10,พันบาท,สำนักงานสถิติแห่งชาติ

In [101]:
size_map = {"ต่ำกว่า 60 ห้อง": 1, "60-149 ห้อง": 2, "150 ห้องขึ้นไป": 3}
df_clean["size_rank"] = df_clean["size_estabish"].map(size_map)
df_clean

,year,region,size_estabish,value,unit,source,size_rank
45,2542,Bangkok,ต่ำกว่า 60 ห้อง,2.970617e+08,พันบาท,สำนักงานสถิติแห่งชาติ,1
46,2544,Bangkok,ต่ำกว่า 60 ห้อง,3.161496e+08,พันบาท,สำนักงานสถิติแห่งชาติ,1
47,2546,Bangkok,ต่ำกว่า 60 ห้อง,2.924750e+08,พันบาท,สำนักงานสถิติแห่งชาติ,1
48,2548,Bangkok,ต่ำกว่า 60 ห้อง,3.187114e+08,พันบาท,สำนักงานสถิติแห่งชาติ,1
49,2550,Bangkok,ต่ำกว่า 60 ห้อง,4.439511e+08,พันบาท,สำนักงานสถิติแห่งชาติ,1
...,...,...,...,...,...,...,...
211,2550,Southern,150 ห้องขึ้นไป,9.014235e+09,พันบาท,สำนักงานสถิติแห่งชาติ,3
212,2552,Southern,150 ห้องขึ้นไป,2.366739e+10,พันบาท,สำนักงานสถิติแห่งชาติ,3
213,2554,Southern,150 ห้องขึ้นไป,1.883257e+10,พันบาท,สำนักงานสถิติแห่งชาติ,3
214,2556,Southern,150 ห้องขึ้นไป,4.430796e+10,พันบาท,สำนักงานสถิติแห่งชาติ,3
215,2558,Southern,150 ห้องขึ้นไป,3.056155e+10,พันบาท,สำนักงานสถิติแห่งชาติ,3

In [102]:
df_clean = df_clean.drop(columns=["unit", "source", "size_estabish"])
df_clean

     year    region         value  size_rank
45   2542   Bangkok  2.970617e+08          1
46   2544   Bangkok  3.161496e+08          1
47   2546   Bangkok  2.924750e+08          1
48   2548   Bangkok  3.187114e+08          1
49   2550   Bangkok  4.439511e+08          1
..    ...       ...           ...        ...
211  2550  Southern  9.014235e+09          3
212  2552  Southern  2.366739e+10          3
213  2554  Southern  1.883257e+10          3
214  2556  Southern  4.430796e+10          3
215  2558  Southern  3.056155e+10          3

[135 rows x 4 columns]

In [103]:
np.random.seed(42)


def simulate_tourists(row):
    year = row["year"]
    region = row["region"]
    # 1. กำหนดเทรนด์นักท่องเที่ยวรวมระดับประเทศ (ล้านคน) ตามช่วงปี
    if year <= 2545:
        base_tourists = 10.0  # ยุคเริ่มต้น
    elif year <= 2550:
        base_tourists = 14.0  # ยุคสนามบินสุวรรณภูมิเปิด
    elif year <= 2555:
        base_tourists = 22.0  # ยุคเติบโต
    elif year <= 2562:
        base_tourists = 35.0  # ยุคก่อนโควิด (พีคสุด)
    elif year <= 2564:
        base_tourists = 6.0  # ยุคโควิด (ตกฮวบ)
    else:
        base_tourists = 28.0  # ยุคฟื้นฟู (ปี 65 เป็นต้นมา)
    # 2. กำหนดสัดส่วนนักท่องเที่ยวตามภูมิภาค (กทม. และ ภาคใต้ เยอะสุด)
    regional_share = {
        "Bangkok": 0.35,  # 35%
        "Southern": 0.25,  # 25%
        "Central": 0.15,  # 15%
        "Northern": 0.15,  # 15%
        "Northeastern": 0.10,  # 10%
    }
    # 3. คำนวณยอดนักท่องเที่ยวของภูมิภาคนั้น + สุ่มค่าความคลาดเคลื่อนนิดหน่อย
    noise = np.random.uniform(-0.5, 0.5)
    tourists_million = (base_tourists * regional_share.get(region, 0.1)) + noise
    # คืนค่ากลับไป (ไม่ให้ค่าติดลบต่ำกว่า 0.1)
    return int(max(0.1, tourists_million) * 1000000)

In [104]:
df_clean["tourists_mn"] = df_clean.apply(simulate_tourists, axis=1)
df_clean

     year    region         value  size_rank  tourists_mn
45   2542   Bangkok  2.970617e+08          1      3374540
46   2544   Bangkok  3.161496e+08          1      3950714
47   2546   Bangkok  2.924750e+08          1      5131993
48   2548   Bangkok  3.187114e+08          1      4998658
49   2550   Bangkok  4.439511e+08          1      4556018
..    ...       ...           ...        ...          ...
211  2550  Southern  9.014235e+09          3      3417411
212  2552  Southern  2.366739e+10          3      5222107
213  2554  Southern  1.883257e+10          3      5119865
214  2556  Southern  4.430796e+10          3      8587615
215  2558  Southern  3.056155e+10          3      9192909

[135 rows x 5 columns]

In [105]:
df_clean.to_csv("../data/processed/datas_cleaned.csv", index=False)
print("Data cleaning completed and saved to ../data/processed/datas_cleaned.csv")

Data cleaning completed and saved to ../data/processed/datas_cleaned.csv