In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/raw/datas.csv")
df = df.copy()
df.columns = df.columns.str.strip()
df

,﻿year,region,size_estabish,value,unit,source
0,2542,ทั่วประเทศ,รวม,46510300.0,พันบาท,สำนักงานสถิติแห่งชาติ
1,2544,ทั่วประเทศ,รวม,47740506.2,พันบาท,สำนักงานสถิติแห่งชาติ
2,2546,ทั่วประเทศ,รวม,57977713.2,พันบาท,สำนักงานสถิติแห่งชาติ
3,2548,ทั่วประเทศ,รวม,57539436.4,พันบาท,สำนักงานสถิติแห่งชาติ
4,2550,ทั่วประเทศ,รวม,73728129.8,พันบาท,สำนักงานสถิติแห่งชาติ
...,...,...,...,...,...,...
211,2550,ภาคใต้,150 ห้องขึ้นไป,9014235.0,พันบาท,สำนักงานสถิติแห่งชาติ
212,2552,ภาคใต้,150 ห้องขึ้นไป,23667391.4,พันบาท,สำนักงานสถิติแห่งชาติ
213,2554,ภาคใต้,150 ห้องขึ้นไป,18832569.3,พันบาท,สำนักงานสถิติแห่งชาติ
214,2556,ภาคใต้,150 ห้องขึ้นไป,44307960.0,พันบาท,สำนักงานสถิติแห่งชาติ
215,2558,ภาคใต้,150 ห้องขึ้นไป,30561545.7,พันบาท,สำนักงานสถิติแห่งชาติ

In [3]:
df = df[~df["region"].str.contains("ทั่วประเทศ", na=False)]
df = df[~df["size_estabish"].str.contains("รวม", na=False)]
df

,﻿year,region,size_estabish,value,unit,source
45,2542,กรุงเทพมหานคร,ต่ำกว่า 60 ห้อง,297061.7,พันบาท,สำนักงานสถิติแห่งชาติ
46,2544,กรุงเทพมหานคร,ต่ำกว่า 60 ห้อง,316149.6,พันบาท,สำนักงานสถิติแห่งชาติ
47,2546,กรุงเทพมหานคร,ต่ำกว่า 60 ห้อง,292475.0,พันบาท,สำนักงานสถิติแห่งชาติ
48,2548,กรุงเทพมหานคร,ต่ำกว่า 60 ห้อง,318711.4,พันบาท,สำนักงานสถิติแห่งชาติ
49,2550,กรุงเทพมหานคร,ต่ำกว่า 60 ห้อง,443951.1,พันบาท,สำนักงานสถิติแห่งชาติ
...,...,...,...,...,...,...
211,2550,ภาคใต้,150 ห้องขึ้นไป,9014235.0,พันบาท,สำนักงานสถิติแห่งชาติ
212,2552,ภาคใต้,150 ห้องขึ้นไป,23667391.4,พันบาท,สำนักงานสถิติแห่งชาติ
213,2554,ภาคใต้,150 ห้องขึ้นไป,18832569.3,พันบาท,สำนักงานสถิติแห่งชาติ
214,2556,ภาคใต้,150 ห้องขึ้นไป,44307960.0,พันบาท,สำนักงานสถิติแห่งชาติ
215,2558,ภาคใต้,150 ห้องขึ้นไป,30561545.7,พันบาท,สำนักงานสถิติแห่งชาติ

In [4]:
region_map = {
    "กรุงเทพมหานคร": "Bangkok",
    "ภาคกลาง": "Central",
    "ภาคเหนือ": "Northern",
    "ภาคตะวันออกเฉียงเหนือ": "Northeastern",
    "ภาคใต้": "Southern",
    "ภาคตะวันออก": "Eastern",
    "ภาคตะวันตก": "Western",
}
df["region"] = df["region"].str.strip().map(region_map).fillna(df["region"])
df

,﻿year,region,size_estabish,value,unit,source
45,2542,Bangkok,ต่ำกว่า 60 ห้อง,297061.7,พันบาท,สำนักงานสถิติแห่งชาติ
46,2544,Bangkok,ต่ำกว่า 60 ห้อง,316149.6,พันบาท,สำนักงานสถิติแห่งชาติ
47,2546,Bangkok,ต่ำกว่า 60 ห้อง,292475.0,พันบาท,สำนักงานสถิติแห่งชาติ
48,2548,Bangkok,ต่ำกว่า 60 ห้อง,318711.4,พันบาท,สำนักงานสถิติแห่งชาติ
49,2550,Bangkok,ต่ำกว่า 60 ห้อง,443951.1,พันบาท,สำนักงานสถิติแห่งชาติ
...,...,...,...,...,...,...
211,2550,Southern,150 ห้องขึ้นไป,9014235.0,พันบาท,สำนักงานสถิติแห่งชาติ
212,2552,Southern,150 ห้องขึ้นไป,23667391.4,พันบาท,สำนักงานสถิติแห่งชาติ
213,2554,Southern,150 ห้องขึ้นไป,18832569.3,พันบาท,สำนักงานสถิติแห่งชาติ
214,2556,Southern,150 ห้องขึ้นไป,44307960.0,พันบาท,สำนักงานสถิติแห่งชาติ
215,2558,Southern,150 ห้องขึ้นไป,30561545.7,พันบาท,สำนักงานสถิติแห่งชาติ

In [5]:
size_symbol_map = {
    "ต่ำกว่า 60 ห้อง": "<60",
    "60-149 ห้อง": "60-149",
    "150 ห้องขึ้นไป": ">150",
}
df["size_estabish"] = (
    df["size_estabish"].str.strip().map(size_symbol_map).fillna(df["size_estabish"])
)
df

     ﻿year    region size_estabish       value    unit                 source
45    2542   Bangkok           <60    297061.7  พันบาท  สำนักงานสถิติแห่งชาติ
46    2544   Bangkok           <60    316149.6  พันบาท  สำนักงานสถิติแห่งชาติ
47    2546   Bangkok           <60    292475.0  พันบาท  สำนักงานสถิติแห่งชาติ
48    2548   Bangkok           <60    318711.4  พันบาท  สำนักงานสถิติแห่งชาติ
49    2550   Bangkok           <60    443951.1  พันบาท  สำนักงานสถิติแห่งชาติ
..     ...       ...           ...         ...     ...                    ...
211   2550  Southern          >150   9014235.0  พันบาท  สำนักงานสถิติแห่งชาติ
212   2552  Southern          >150  23667391.4  พันบาท  สำนักงานสถิติแห่งชาติ
213   2554  Southern          >150  18832569.3  พันบาท  สำนักงานสถิติแห่งชาติ
214   2556  Southern          >150  44307960.0  พันบาท  สำนักงานสถิติแห่งชาติ
215   2558  Southern          >150  30561545.7  พันบาท  สำนักงานสถิติแห่งชาติ

[135 rows x 6 columns]

In [6]:
df["value"] = pd.to_numeric(df["value"], errors="coerce") * 1000
df

,﻿year,region,size_estabish,value,unit,source
45,2542,Bangkok,<60,2.970617e+08,พันบาท,สำนักงานสถิติแห่งชาติ
46,2544,Bangkok,<60,3.161496e+08,พันบาท,สำนักงานสถิติแห่งชาติ
47,2546,Bangkok,<60,2.924750e+08,พันบาท,สำนักงานสถิติแห่งชาติ
48,2548,Bangkok,<60,3.187114e+08,พันบาท,สำนักงานสถิติแห่งชาติ
49,2550,Bangkok,<60,4.439511e+08,พันบาท,สำนักงานสถิติแห่งชาติ
...,...,...,...,...,...,...
211,2550,Southern,>150,9.014235e+09,พันบาท,สำนักงานสถิติแห่งชาติ
212,2552,Southern,>150,2.366739e+10,พันบาท,สำนักงานสถิติแห่งชาติ
213,2554,Southern,>150,1.883257e+10,พันบาท,สำนักงานสถิติแห่งชาติ
214,2556,Southern,>150,4.430796e+10,พันบาท,สำนักงานสถิติแห่งชาติ
215,2558,Southern,>150,3.056155e+10,พันบาท,สำนักงานสถิติแห่งชาติ

In [7]:
df = df.drop(columns=["unit", "source"], errors="ignore")
df

     ﻿year    region size_estabish         value
45    2542   Bangkok           <60  2.970617e+08
46    2544   Bangkok           <60  3.161496e+08
47    2546   Bangkok           <60  2.924750e+08
48    2548   Bangkok           <60  3.187114e+08
49    2550   Bangkok           <60  4.439511e+08
..     ...       ...           ...           ...
211   2550  Southern          >150  9.014235e+09
212   2552  Southern          >150  2.366739e+10
213   2554  Southern          >150  1.883257e+10
214   2556  Southern          >150  4.430796e+10
215   2558  Southern          >150  3.056155e+10

[135 rows x 4 columns]

In [8]:
rank_map = {"<60": 1, "60-149": 2, ">150": 3}
df["size_rank"] = df["size_estabish"].map(rank_map)
df

     ﻿year    region size_estabish         value  size_rank
45    2542   Bangkok           <60  2.970617e+08          1
46    2544   Bangkok           <60  3.161496e+08          1
47    2546   Bangkok           <60  2.924750e+08          1
48    2548   Bangkok           <60  3.187114e+08          1
49    2550   Bangkok           <60  4.439511e+08          1
..     ...       ...           ...           ...        ...
211   2550  Southern          >150  9.014235e+09          3
212   2552  Southern          >150  2.366739e+10          3
213   2554  Southern          >150  1.883257e+10          3
214   2556  Southern          >150  4.430796e+10          3
215   2558  Southern          >150  3.056155e+10          3

[135 rows x 5 columns]

In [9]:
df.to_csv("../data/processed/datas_cleaned.csv", index=False)
print("Data cleaning completed and saved to ../data/processed/datas_cleaned.csv")

Data cleaning completed and saved to ../data/processed/datas_cleaned.csv