In [1]:
from autogluon.tabular import TabularDataset, TabularPredictor
import pandas as pd

In [2]:
save_path = "../AutogluonModels/TabularPredictor"
df = pd.read_csv("../data/processed/datas_cleaned.csv")
df.head()

   year   region size_estabish        value  size_rank
0  2542  Bangkok           <60  297061700.0          1
1  2544  Bangkok           <60  316149600.0          1
2  2546  Bangkok           <60  292475000.0          1
3  2548  Bangkok           <60  318711400.0          1
4  2550  Bangkok           <60  443951100.0          1

In [3]:
train_data = TabularDataset(df[df["year"] <= 2554].drop(columns=["size_estabish"]))
test_data = TabularDataset(df[df["year"] >= 2556].drop(columns=["size_estabish"]))

In [4]:
train_data["value"].describe()

count    1.050000e+02
mean     5.046461e+09
std      7.965187e+09
min      2.223934e+08
25%      8.673075e+08
50%      1.726217e+09
75%      5.033558e+09
max      3.997165e+10
Name: value, dtype: float64

In [5]:
predictor = TabularPredictor(
    label="value", problem_type="regression", path=save_path
).fit(
    train_data,
    presets="good_quality",
)

Warning: path already exists! This predictor may overwrite an existing predictor! path="../AutogluonModels/TabularPredictor"
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.12.10
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.26200
CPU Count:          20
Pytorch Version:    2.9.1+cpu
CUDA Version:       CUDA is not available
Memory Avail:       6.91 GB / 15.73 GB (44.0%)
Disk Space Avail:   636.31 GB / 953.85 GB (66.7%)
===================================================
Presets specified: ['good_quality']
Using hyperparameters preset: hyperparameters='light'
Setting dynamic_stacking from 'auto' to True. Reason: Enable dynamic_stacking when use_bag_holdout is disabled. (use_bag_holdout=False)
Stack configuration (auto_stack=True): num_stack_levels=1, num_bag_folds=8, num_bag_sets=1
Note: `save_bag_folds=False`! This will greatly reduce peak disk usage during fit (by ~8x), but runs the risk of an out-of-memory error during model refit if memory is small relative to the data size.
	You can avoid this risk by setting `save_bag_folds=True`.
DyStack is enabled (dynamic_stacking=True). AutoGluon will try to determine whether the input data is affected by stacked overfitting and enable or disable stacking as a consequence.
	This is used to identify the optimal `num_stack_levels` value. Copies of AutoGluon will be fit on subsets of the data. Then holdout validation data is used to detect stacked overfitting.
	Running DyStack for up to 900s of the 3600s of remaining time (25%).
	Running DyStack sub-fit in a ray process to avoid memory leakage. Enabling ray logging (enable_ray_logging=True). Specify `ds_args={'enable_ray_logging': False}` if you experience logging issues.
2026-03-07 20:50:29,946	INFO worker.py:2014 -- Started a local Ray instance. View the dashboard at http://127.0.0.1:8265
d:\Mini Project\Term Project\.venv\Lib\site-packages\ray\_private\worker.py:2062: FutureWarning: Tip: In future versions of Ray, Ray will no longer override accelerator visible devices env var if num_gpus=0 or num_gpus=None (default). To enable this behavior and turn off this error message, set RAY_ACCEL_ENV_VAR_OVERRIDE_ON_ZERO=0
  warnings.warn(
		Context path: "d:\Mini Project\Term Project\AutogluonModels\TabularPredictor\ds_sub_fit\sub_fit_ho"
(_dystack pid=24440) Running DyStack sub-fit ...
(_dystack pid=24440) Beginning AutoGluon training ... Time limit = 893s
(_dystack pid=24440) AutoGluon will save models to "d:\Mini Project\Term Project\AutogluonModels\TabularPredictor\ds_sub_fit\sub_fit_ho"
(_dystack pid=24440) Train Data Rows:    93
(_dystack pid=24440) Train Data Columns: 3
(_dystack pid=24440) Label Column:       value
(_dystack pid=24440) Problem Type:       regression
(_dystack pid=24440) Preprocessing data ...
(_dystack pid=24440) Using Feature Generators to preprocess the data ...
(_dystack pid=24440) Fitting AutoMLPipelineFeatureGenerator...
(_dystack pid=24440) 	Available Memory:                    5846.60 MB
(_dystack pid=24440) 	Train Data (Original)  Memory Usage: 0.01 MB (0.0% of available memory)
(_dystack pid=24440) 	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
(_dystack pid=24440) 	Stage 1 Generators:
(_dystack pid=24440) 		Fitting AsTypeFeatureGenerator...
(_dystack pid=24440) 	Stage 2 Generators:
(_dystack pid=24440) 		Fitting FillNaFeatureGenerator...
(_dystack pid=24440) 	Stage 3 Generators:
(_dystack pid=24440) 		Fitting IdentityFeatureGenerator...
(_dystack pid=24440) 		Fitting CategoryFeatureGenerator...
(_dystack pid=24440) 			Fitting CategoryMemoryMinimizeFeatureGenerator...
(_dystack pid=24440) 	Stage 4 Generators:
(_dystack pid=24440) 		Fitting DropUniqueFeatureGenerator...
(_dystack pid=24440) 	Stage 5 Generators:
(_dystack pid=24440) 		Fitting DropDuplicatesFeatureGenerator...
(_dystack pid=24440) 	Types of features in original data (raw dtype, special dtypes):
(_dystack pid=24440) 		('int', [])    : 2 | ['year', 'size_rank']
(_dystack pid=24440) 		('object', []) : 1 | ['region']
(_dystack pid=24440) 	Types of features in processed data (raw dtype, special dtypes):
(_dystack pid=24440) 		('category', []) : 1 | ['region']
(_dystack pid=24440) 		('int', [])      : 2 | ['year', 'size_rank']
(_dystack pid=24440) 	0.0s = Fit runtime
(_dystack pid=24440) 	3 features in original data used to generate 3 features in processed data.
(_dystack pid=24440) 	Train Data (Processed) Memory Usage: 0.00 MB (0.0% of available memory)
(_dystack pid=24440) Data preprocessing and feature engineering runtime = 0.02s ...
(_dystack pid=24440) AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
(_dystack pid=24440) 	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
(_dystack pid=24440) 	To change this, specify the eval_metric parameter of Predictor()
(_dystack pid=24440) User-specified model hyperparameters to be fit:
(_dystack pid=24440) {
(_dystack pid=24440) 	'NN_TORCH': [{}],
(_dystack pid=24440) 	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
(_dystack pid=24440) 	'CAT': [{}],
(_dystack pid=24440) 	'XGB': [{}],
(_dystack pid=24440) 	'FASTAI': [{}],
(_dystack pid=24440) 	'RF': [{'criterion': 'gini', 'max_depth': 15, 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'max_depth': 15, 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'max_depth': 15, 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
(_dystack pid=24440) 	'XT': [{'criterion': 'gini', 'max_depth': 15, 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'max_depth': 15, 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'max_depth': 15, 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
(_dystack pid=24440) }
(_dystack pid=24440) AutoGluon will fit 2 stack levels (L1 to L2) ...
(_dystack pid=24440) Fitting 9 L1 models, fit_strategy="sequential" ...
(_dystack pid=24440) Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 595.47s of the 893.43s of remaining time.
(_dystack pid=24440) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.26%)

(_ray_fit pid=27028) [1000]	valid_set's rmse: 3.12965e+09

(_dystack pid=24440) 	-7091822093.6443	 = Validation score   (-root_mean_squared_error)
(_dystack pid=24440) 	1.08s	 = Training   runtime
(_dystack pid=24440) 	0.02s	 = Validation runtime
(_dystack pid=24440) Fitting model: LightGBM_BAG_L1 ... Training model for up to 588.30s of the 886.26s of remaining time.
(_dystack pid=24440) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.34%)
(_dystack pid=24440) 	-6544775955.7193	 = Validation score   (-root_mean_squared_error)
(_dystack pid=24440) 	0.46s	 = Training   runtime
(_dystack pid=24440) 	0.02s	 = Validation runtime
(_dystack pid=24440) Fitting model: RandomForestMSE_BAG_L1 ... Training model for up to 584.03s of the 881.99s of remaining time.
(_dystack pid=24440) 	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=20, gpus=0
(_dystack pid=24440) 	-3084016045.3628	 = Validation score   (-root_mean_squared_error)
(_dystack pid=24440) 	0.51s	 = Training   runtime
(_dystack pid=24440) 	0.07s	 = Validation runtime
(_dystack pid=24440) Fitting model: CatBoost_BAG_L1 ... Training model for up to 583.41s of the 881.37s of remaining time.
(_dystack pid=24440) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=8.45%)
(_dystack pid=24440) 	-3220848020.9464	 = Validation score   (-root_mean_squared_error)
(_dystack pid=24440) 	270.71s	 = Training   runtime
(_dystack pid=24440) 	0.02s	 = Validation runtime
(_dystack pid=24440) Fitting model: ExtraTreesMSE_BAG_L1 ... Training model for up to 309.17s of the 607.13s of remaining time.
(_dystack pid=24440) 	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=20, gpus=0
(_dystack pid=24440) 	-3306315076.3648	 = Validation score   (-root_mean_squared_error)
(_dystack pid=24440) 	0.32s	 = Training   runtime
(_dystack pid=24440) 	0.04s	 = Validation runtime
(_dystack pid=24440) Fitting model: NeuralNetFastAI_BAG_L1 ... Training model for up to 308.75s of the 606.71s of remaining time.
(_dystack pid=24440) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.00%)
(_ray_fit pid=6496) No improvement since epoch 8: early stopping
(_dystack pid=24440) 	-3875879500.4085	 = Validation score   (-root_mean_squared_error)
(_dystack pid=24440) 	6.04s	 = Training   runtime
(_dystack pid=24440) 	0.05s	 = Validation runtime
(_dystack pid=24440) Fitting model: XGBoost_BAG_L1 ... Training model for up to 299.77s of the 597.73s of remaining time.
(_dystack pid=24440) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.13%)
(_dystack pid=24440) 	-2695962931.8325	 = Validation score   (-root_mean_squared_error)
(_dystack pid=24440) 	2.16s	 = Training   runtime
(_dystack pid=24440) 	0.03s	 = Validation runtime
(_dystack pid=24440) Fitting model: NeuralNetTorch_BAG_L1 ... Training model for up to 293.99s of the 591.95s of remaining time.
(_dystack pid=24440) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.00%)
(_ray_fit pid=17444) d:\Mini Project\Term Project\.venv\Lib\site-packages\sklearn\compose\_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
(_ray_fit pid=17444)   warnings.warn(
(_dystack pid=24440) 	-4534314380.5468	 = Validation score   (-root_mean_squared_error)
(_dystack pid=24440) 	11.22s	 = Training   runtime
(_dystack pid=24440) 	0.03s	 = Validation runtime
(_dystack pid=24440) Fitting model: LightGBMLarge_BAG_L1 ... Training model for up to 279.84s of the 577.80s of remaining time.
(_dystack pid=24440) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=1.11%)
(_ray_fit pid=34796) d:\Mini Project\Term Project\.venv\Lib\site-packages\sklearn\compose\_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning. [repeated 7x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/user-guides/configure-logging.html#log-deduplication for more options.)
(_ray_fit pid=34796)   warnings.warn( [repeated 7x across cluster]
(_dystack pid=24440) 	-7036220655.0335	 = Validation score   (-root_mean_squared_error)
(_dystack pid=24440) 	0.41s	 = Training   runtime
(_dystack pid=24440) 	0.01s	 = Validation runtime
(_dystack pid=24440) Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 574.33s of remaining time.
(_dystack pid=24440) 	Fitting 1 model on all data | Fitting with cpus=20, gpus=0, mem=0.0/4.6 GB
(_dystack pid=24440) 	Ensemble Weights: {'XGBoost_BAG_L1': 0.857, 'RandomForestMSE_BAG_L1': 0.071, 'CatBoost_BAG_L1': 0.071}
(_dystack pid=24440) 	-2687157252.8785	 = Validation score   (-root_mean_squared_error)
(_dystack pid=24440) 	0.0s	 = Training   runtime
(_dystack pid=24440) 	0.0s	 = Validation runtime
(_dystack pid=24440) Fitting 9 L2 models, fit_strategy="sequential" ...
(_dystack pid=24440) Fitting model: LightGBMXT_BAG_L2 ... Training model for up to 574.32s of the 574.31s of remaining time.
(_dystack pid=24440) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.36%)
(_dystack pid=24440) 	-4737133967.7141	 = Validation score   (-root_mean_squared_error)
(_dystack pid=24440) 	0.5s	 = Training   runtime
(_dystack pid=24440) 	0.01s	 = Validation runtime
(_dystack pid=24440) Fitting model: LightGBM_BAG_L2 ... Training model for up to 570.68s of the 570.68s of remaining time.
(_dystack pid=24440) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.36%)
(_dystack pid=24440) 	-4551877397.0239	 = Validation score   (-root_mean_squared_error)
(_dystack pid=24440) 	0.51s	 = Training   runtime
(_dystack pid=24440) 	0.02s	 = Validation runtime
(_dystack pid=24440) Fitting model: RandomForestMSE_BAG_L2 ... Training model for up to 566.95s of the 566.95s of remaining time.
(_dystack pid=24440) 	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=20, gpus=0
(_dystack pid=24440) 	-3021468850.506	 = Validation score   (-root_mean_squared_error)
(_dystack pid=24440) 	0.47s	 = Training   runtime
(_dystack pid=24440) 	0.09s	 = Validation runtime
(_dystack pid=24440) Fitting model: CatBoost_BAG_L2 ... Training model for up to 566.37s of the 566.36s of remaining time.
(_dystack pid=24440) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=8.48%)
(_dystack pid=24440) 	-3300611521.9296	 = Validation score   (-root_mean_squared_error)
(_dystack pid=24440) 	27.99s	 = Training   runtime
(_dystack pid=24440) 	0.02s	 = Validation runtime
(_dystack pid=24440) Fitting model: ExtraTreesMSE_BAG_L2 ... Training model for up to 535.31s of the 535.31s of remaining time.
(_dystack pid=24440) 	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=20, gpus=0
(_dystack pid=24440) 	-2789310661.7897	 = Validation score   (-root_mean_squared_error)
(_dystack pid=24440) 	0.34s	 = Training   runtime
(_dystack pid=24440) 	0.04s	 = Validation runtime
(_dystack pid=24440) Fitting model: NeuralNetFastAI_BAG_L2 ... Training model for up to 534.92s of the 534.92s of remaining time.
(_dystack pid=24440) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.00%)
(_ray_fit pid=7956) No improvement since epoch 6: early stopping
(_dystack pid=24440) 	-2653700777.7804	 = Validation score   (-root_mean_squared_error)
(_dystack pid=24440) 	6.38s	 = Training   runtime
(_dystack pid=24440) 	0.07s	 = Validation runtime
(_dystack pid=24440) Fitting model: XGBoost_BAG_L2 ... Training model for up to 525.73s of the 525.73s of remaining time.
(_dystack pid=24440) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.22%)
(_dystack pid=24440) 	-3457234918.9954	 = Validation score   (-root_mean_squared_error)
(_dystack pid=24440) 	0.53s	 = Training   runtime
(_dystack pid=24440) 	0.03s	 = Validation runtime
(_dystack pid=24440) Fitting model: NeuralNetTorch_BAG_L2 ... Training model for up to 521.63s of the 521.63s of remaining time.
(_dystack pid=24440) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.00%)
(_ray_fit pid=34784) d:\Mini Project\Term Project\.venv\Lib\site-packages\sklearn\compose\_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
(_ray_fit pid=34784)   warnings.warn(
(_ray_fit pid=14008) No improvement since epoch 8: early stopping
(_dystack pid=24440) 	-2984089712.8765	 = Validation score   (-root_mean_squared_error)
(_dystack pid=24440) 	6.51s	 = Training   runtime
(_dystack pid=24440) 	0.07s	 = Validation runtime
(_dystack pid=24440) Fitting model: LightGBMLarge_BAG_L2 ... Training model for up to 511.71s of the 511.71s of remaining time.
(_dystack pid=24440) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=2.05%)

(_ray_fit pid=21936) [1000]	valid_set's rmse: 1.80819e+09 [repeated 12x across cluster]

(_dystack pid=24440) 	-3470721042.7922	 = Validation score   (-root_mean_squared_error)
(_dystack pid=24440) 	0.65s	 = Training   runtime
(_dystack pid=24440) 	0.02s	 = Validation runtime
(_ray_fit pid=15264) d:\Mini Project\Term Project\.venv\Lib\site-packages\sklearn\compose\_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning. [repeated 7x across cluster]
(_ray_fit pid=15264)   warnings.warn( [repeated 7x across cluster]
(_dystack pid=24440) Fitting model: WeightedEnsemble_L3 ... Training model for up to 360.00s of the 507.46s of remaining time.
(_dystack pid=24440) 	Fitting 1 model on all data | Fitting with cpus=20, gpus=0, mem=0.0/4.5 GB
(_dystack pid=24440) 	Ensemble Weights: {'NeuralNetFastAI_BAG_L2': 0.529, 'XGBoost_BAG_L1': 0.412, 'ExtraTreesMSE_BAG_L2': 0.059}
(_dystack pid=24440) 	-2550151482.25	 = Validation score   (-root_mean_squared_error)
(_dystack pid=24440) 	0.01s	 = Training   runtime
(_dystack pid=24440) 	0.0s	 = Validation runtime
(_dystack pid=24440) AutoGluon training complete, total runtime = 386.01s ... Best model: WeightedEnsemble_L3 | Estimated inference throughput: 52.6 rows/s (12 batch size)
(_dystack pid=24440) Automatically performing refit_full as a post-fit operation (due to `.fit(..., refit_full=True)`
(_dystack pid=24440) Refitting models via `predictor.refit_full` using all of the data (combined train and validation)...
(_dystack pid=24440) 	Models trained in this way will have the suffix "_FULL" and have NaN validation score.
(_dystack pid=24440) 	This process is not bound by time_limit, but should take less time than the original `predictor.fit` call.
(_dystack pid=24440) 	To learn more, refer to the `.refit_full` method docstring which explains how "_FULL" models differ from normal models.
(_dystack pid=24440) Fitting 1 L1 models, fit_strategy="sequential" ...
(_dystack pid=24440) Fitting model: LightGBMXT_BAG_L1_FULL ...
(_dystack pid=24440) 	Fitting 1 model on all data | Fitting with cpus=20, gpus=0, mem=0.0/4.6 GB
(_dystack pid=24440) 	0.62s	 = Training   runtime
(_dystack pid=24440) Fitting 1 L1 models, fit_strategy="sequential" ...
(_dystack pid=24440) Fitting model: LightGBM_BAG_L1_FULL ...
(_dystack pid=24440) 	Fitting 1 model on all data | Fitting with cpus=20, gpus=0, mem=0.0/5.5 GB
(_dystack pid=24440) 	0.17s	 = Training   runtime
(_dystack pid=24440) Fitting model: RandomForestMSE_BAG_L1_FULL | Skipping fit via cloning parent ...
(_dystack pid=24440) 	0.51s	 = Training   runtime
(_dystack pid=24440) 	0.07s	 = Validation runtime
(_dystack pid=24440) Fitting 1 L1 models, fit_strategy="sequential" ...
(_dystack pid=24440) Fitting model: CatBoost_BAG_L1_FULL ...
(_dystack pid=24440) 	Fitting 1 model on all data | Fitting with cpus=20, gpus=0
(_dystack pid=24440) 	38.27s	 = Training   runtime
(_dystack pid=24440) Fitting model: ExtraTreesMSE_BAG_L1_FULL | Skipping fit via cloning parent ...
(_dystack pid=24440) 	0.32s	 = Training   runtime
(_dystack pid=24440) 	0.04s	 = Validation runtime
(_dystack pid=24440) Fitting 1 L1 models, fit_strategy="sequential" ...
(_dystack pid=24440) Fitting model: NeuralNetFastAI_BAG_L1_FULL ...
(_dystack pid=24440) 	Fitting 1 model on all data | Fitting with cpus=14, gpus=0, mem=0.0/5.8 GB
(_dystack pid=24440) 	Stopping at the best epoch learned earlier - 22.
(_dystack pid=24440) 	0.39s	 = Training   runtime
(_dystack pid=24440) Fitting 1 L1 models, fit_strategy="sequential" ...
(_dystack pid=24440) Fitting model: XGBoost_BAG_L1_FULL ...
(_dystack pid=24440) 	Fitting 1 model on all data | Fitting with cpus=20, gpus=0
(_dystack pid=24440) 	0.54s	 = Training   runtime
(_dystack pid=24440) Fitting 1 L1 models, fit_strategy="sequential" ...
(_dystack pid=24440) Fitting model: NeuralNetTorch_BAG_L1_FULL ...
(_dystack pid=24440) 	Fitting 1 model on all data | Fitting with cpus=14, gpus=0, mem=0.0/5.6 GB
(_dystack pid=24440) d:\Mini Project\Term Project\.venv\Lib\site-packages\sklearn\compose\_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
(_dystack pid=24440)   warnings.warn(
(_dystack pid=24440) 	2.47s	 = Training   runtime
(_dystack pid=24440) Fitting 1 L1 models, fit_strategy="sequential" ...
(_dystack pid=24440) Fitting model: LightGBMLarge_BAG_L1_FULL ...
(_dystack pid=24440) 	Fitting 1 model on all data | Fitting with cpus=20, gpus=0, mem=0.0/5.6 GB
(_dystack pid=24440) 	0.15s	 = Training   runtime
(_dystack pid=24440) Fitting model: WeightedEnsemble_L2_FULL | Skipping fit via cloning parent ...
(_dystack pid=24440) 	Ensemble Weights: {'XGBoost_BAG_L1': 0.857, 'RandomForestMSE_BAG_L1': 0.071, 'CatBoost_BAG_L1': 0.071}
(_dystack pid=24440) 	0.0s	 = Training   runtime
(_dystack pid=24440) Fitting 1 L2 models, fit_strategy="sequential" ...
(_dystack pid=24440) Fitting model: LightGBMXT_BAG_L2_FULL ...
(_dystack pid=24440) 	Fitting 1 model on all data | Fitting with cpus=20, gpus=0, mem=0.0/5.6 GB
(_dystack pid=24440) 	0.14s	 = Training   runtime
(_dystack pid=24440) Fitting 1 L2 models, fit_strategy="sequential" ...
(_dystack pid=24440) Fitting model: LightGBM_BAG_L2_FULL ...
(_dystack pid=24440) 	Fitting 1 model on all data | Fitting with cpus=20, gpus=0, mem=0.0/5.6 GB
(_dystack pid=24440) 	0.13s	 = Training   runtime
(_dystack pid=24440) Fitting model: RandomForestMSE_BAG_L2_FULL | Skipping fit via cloning parent ...
(_dystack pid=24440) 	0.47s	 = Training   runtime
(_dystack pid=24440) 	0.09s	 = Validation runtime
(_dystack pid=24440) Fitting 1 L2 models, fit_strategy="sequential" ...
(_dystack pid=24440) Fitting model: CatBoost_BAG_L2_FULL ...
(_dystack pid=24440) 	Fitting 1 model on all data | Fitting with cpus=20, gpus=0
(_dystack pid=24440) 	4.78s	 = Training   runtime
(_dystack pid=24440) Fitting model: ExtraTreesMSE_BAG_L2_FULL | Skipping fit via cloning parent ...
(_dystack pid=24440) 	0.34s	 = Training   runtime
(_dystack pid=24440) 	0.04s	 = Validation runtime
(_dystack pid=24440) Fitting 1 L2 models, fit_strategy="sequential" ...
(_dystack pid=24440) Fitting model: NeuralNetFastAI_BAG_L2_FULL ...
(_dystack pid=24440) 	Fitting 1 model on all data | Fitting with cpus=14, gpus=0, mem=0.0/5.6 GB
(_dystack pid=24440) 	Stopping at the best epoch learned earlier - 14.
(_dystack pid=24440) 	0.27s	 = Training   runtime
(_dystack pid=24440) Fitting 1 L2 models, fit_strategy="sequential" ...
(_dystack pid=24440) Fitting model: XGBoost_BAG_L2_FULL ...
(_dystack pid=24440) 	Fitting 1 model on all data | Fitting with cpus=20, gpus=0
(_dystack pid=24440) 	0.03s	 = Training   runtime
(_dystack pid=24440) Fitting 1 L2 models, fit_strategy="sequential" ...
(_dystack pid=24440) Fitting model: NeuralNetTorch_BAG_L2_FULL ...
(_dystack pid=24440) 	Fitting 1 model on all data | Fitting with cpus=14, gpus=0, mem=0.0/5.6 GB
(_dystack pid=24440) d:\Mini Project\Term Project\.venv\Lib\site-packages\sklearn\compose\_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
(_dystack pid=24440)   warnings.warn(
(_dystack pid=24440) 	0.39s	 = Training   runtime
(_dystack pid=24440) Fitting 1 L2 models, fit_strategy="sequential" ...
(_dystack pid=24440) Fitting model: LightGBMLarge_BAG_L2_FULL ...
(_dystack pid=24440) 	Fitting 1 model on all data | Fitting with cpus=20, gpus=0, mem=0.0/5.6 GB
(_dystack pid=24440) 	0.25s	 = Training   runtime
(_dystack pid=24440) Fitting model: WeightedEnsemble_L3_FULL | Skipping fit via cloning parent ...
(_dystack pid=24440) 	Ensemble Weights: {'NeuralNetFastAI_BAG_L2': 0.529, 'XGBoost_BAG_L1': 0.412, 'ExtraTreesMSE_BAG_L2': 0.059}
(_dystack pid=24440) 	0.01s	 = Training   runtime
(_dystack pid=24440) Updated best model to "WeightedEnsemble_L3_FULL" (Previously "WeightedEnsemble_L3"). AutoGluon will default to using "WeightedEnsemble_L3_FULL" for predict() and predict_proba().
(_dystack pid=24440) Refit complete, total runtime = 52.67s ... Best model: "WeightedEnsemble_L3_FULL"
(_dystack pid=24440) TabularPredictor saved. To load, use: predictor = TabularPredictor.load("d:\Mini Project\Term Project\AutogluonModels\TabularPredictor\ds_sub_fit\sub_fit_ho")
(_dystack pid=24440) Deleting DyStack predictor artifacts (clean_up_fits=True) ...
Leaderboard on holdout data (DyStack):
                          model  score_holdout     score_val              eval_metric  pred_time_test  pred_time_val   fit_time  pred_time_test_marginal  pred_time_val_marginal  fit_time_marginal  stack_level  can_infer  fit_order
0   RandomForestMSE_BAG_L1_FULL  -3.506215e+09 -3.084016e+09  root_mean_squared_error        0.072547       0.066519   0.506728                 0.072547                0.066519           0.506728            1       True          3
1          CatBoost_BAG_L2_FULL  -3.532523e+09 -3.300612e+09  root_mean_squared_error        0.299604            NaN  47.442544                 0.028006                     NaN           4.778156            2       True         14
2     ExtraTreesMSE_BAG_L2_FULL  -3.690529e+09 -2.789311e+09  root_mean_squared_error        0.337145            NaN  43.001593                 0.065547                0.042042           0.337205            2       True         15
3           XGBoost_BAG_L2_FULL  -3.707833e+09 -3.457235e+09  root_mean_squared_error        0.318105            NaN  42.696406                 0.046508                     NaN           0.032018            2       True         17
4   RandomForestMSE_BAG_L2_FULL  -3.749533e+09 -3.021469e+09  root_mean_squared_error        0.361256            NaN  43.136240                 0.089658                0.086511           0.471852            2       True         13
5    NeuralNetTorch_BAG_L1_FULL  -3.771693e+09 -4.534314e+09  root_mean_squared_error        0.021999            NaN   2.471325                 0.021999                     NaN           2.471325            1       True          8
6    NeuralNetTorch_BAG_L2_FULL  -3.780536e+09 -2.984090e+09  root_mean_squared_error        0.311597            NaN  43.051429                 0.039999                     NaN           0.387041            2       True         18
7      WeightedEnsemble_L2_FULL  -4.100782e+09 -2.687157e+09  root_mean_squared_error        0.160062            NaN  39.317752                 0.017004                     NaN           0.004998            2       True         10
8     ExtraTreesMSE_BAG_L1_FULL  -4.117823e+09 -3.306315e+09  root_mean_squared_error        0.050526       0.041896   0.322712                 0.050526                0.041896           0.322712            1       True          5
9           XGBoost_BAG_L1_FULL  -4.154254e+09 -2.695963e+09  root_mean_squared_error        0.052510            NaN   0.536468                 0.052510                     NaN           0.536468            1       True          7
10         CatBoost_BAG_L1_FULL  -4.256562e+09 -3.220848e+09  root_mean_squared_error        0.018000            NaN  38.269558                 0.018000                     NaN          38.269558            1       True          4
11    LightGBMLarge_BAG_L2_FULL  -4.348799e+09 -3.470721e+09  root_mean_squared_error        0.312600            NaN  42.912460                 0.041002                     NaN           0.248072            2       True         19
12     WeightedEnsemble_L3_FULL  -4.764111e+09 -2.550151e+09  root_mean_squared_error        0.399650            NaN  43.279384                 0.016507                     NaN           0.006001            3       True         20
13  NeuralNetFastAI_BAG_L2_FULL  -5.545041e+09 -2.653701e+09  root_mean_squared_error        0.317595            NaN  42.936179                 0.045998                     NaN           0.271791            2       True         16
14  NeuralNetFastAI_BAG_L1_FULL  -5.875212e+09 -3.875880e+09  root_mean_squared_error        0.031017            NaN   0.391945                 0.031017                     NaN           0.391945            1       True          6
15         LightGBM_BAG_L2_FULL  -6.757831e+09 -4.551877e+09  root_mean_squared_error        0.308599            NaN  42.793184                 0.037001                     NaN           0.128796            2       True         12
16       LightGBMXT_BAG_L2_FULL  -6.999676e+09 -4.737134e+09  root_mean_squared_error        0.306485            NaN  42.804438                 0.034888                     NaN           0.140050            2       True         11
17         LightGBM_BAG_L1_FULL  -9.652794e+09 -6.544776e+09  root_mean_squared_error        0.024997            NaN   0.165652                 0.024997                     NaN           0.165652            1       True          2
18    LightGBMLarge_BAG_L1_FULL  -1.053598e+10 -7.036221e+09  root_mean_squared_error        0.022001            NaN   0.151105                 0.022001                     NaN           0.151105            1       True          9
19       LightGBMXT_BAG_L1_FULL  -1.113922e+10 -7.091822e+09  root_mean_squared_error        0.032037            NaN   0.615275                 0.032037                     NaN           0.615275            1       True          1
	0	 = Optimal   num_stack_levels (Stacked Overfitting Occurred: True)
	449s	 = DyStack   runtime |	3151s	 = Remaining runtime
Starting main fit with num_stack_levels=0.
	For future fit calls on this dataset, you can skip DyStack to save time: `predictor.fit(..., dynamic_stacking=False, num_stack_levels=0)`
Beginning AutoGluon training ... Time limit = 3151s
AutoGluon will save models to "d:\Mini Project\Term Project\AutogluonModels\TabularPredictor"
Train Data Rows:    105
Train Data Columns: 3
Label Column:       value
Problem Type:       regression
Preprocessing data ...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    5713.09 MB
	Train Data (Original)  Memory Usage: 0.01 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('int', [])    : 2 | ['year', 'size_rank']
		('object', []) : 1 | ['region']
	Types of features in processed data (raw dtype, special dtypes):
		('category', []) : 1 | ['region']
		('int', [])      : 2 | ['year', 'size_rank']
	0.0s = Fit runtime
	3 features in original data used to generate 3 features in processed data.
	Train Data (Processed) Memory Usage: 0.00 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.03s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'max_depth': 15, 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'max_depth': 15, 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'max_depth': 15, 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'max_depth': 15, 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'max_depth': 15, 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'max_depth': 15, 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 9 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 3151.33s of the 3151.33s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.24%)
	-7511733858.0434	 = Validation score   (-root_mean_squared_error)
	0.46s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBM_BAG_L1 ... Training model for up to 3146.42s of the 3146.42s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.31%)
	-6760417175.7901	 = Validation score   (-root_mean_squared_error)
	1.74s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: RandomForestMSE_BAG_L1 ... Training model for up to 3141.61s of the 3141.61s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=20, gpus=0
	-3221725925.8932	 = Validation score   (-root_mean_squared_error)
	0.56s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: CatBoost_BAG_L1 ... Training model for up to 3140.96s of the 3140.96s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=6.00%)
	-3572457272.133	 = Validation score   (-root_mean_squared_error)
	161.05s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: ExtraTreesMSE_BAG_L1 ... Training model for up to 2977.39s of the 2977.39s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=20, gpus=0
	-3271058364.393	 = Validation score   (-root_mean_squared_error)
	0.34s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: NeuralNetFastAI_BAG_L1 ... Training model for up to 2976.97s of the 2976.97s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.00%)
	-4292748597.9467	 = Validation score   (-root_mean_squared_error)
	7.5s	 = Training   runtime
	0.07s	 = Validation runtime
Fitting model: XGBoost_BAG_L1 ... Training model for up to 2967.18s of the 2967.18s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.10%)
	-3116125432.128	 = Validation score   (-root_mean_squared_error)
	1.67s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: NeuralNetTorch_BAG_L1 ... Training model for up to 2962.39s of the 2962.39s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.00%)
	-4689785259.4096	 = Validation score   (-root_mean_squared_error)
	10.52s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: LightGBMLarge_BAG_L1 ... Training model for up to 2949.02s of the 2949.02s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=1.10%)
	-7310346295.8463	 = Validation score   (-root_mean_squared_error)
	1.41s	 = Training   runtime
	0.01s	 = Validation runtime

In [6]:
predictor.evaluate(test_data)

{'root_mean_squared_error': np.float64(-7722535144.447288),
 'mean_squared_error': -5.963754905722348e+19,
 'mean_absolute_error': -4913063376.666667,
 'r2': 0.6029729238362012,
 'pearsonr': 0.838044041972232,
 'median_absolute_error': -2478005030.0}

In [7]:
predictor.leaderboard(test_data)

,model,score_test,score_val,eval_metric,pred_time_test,pred_time_val,fit_time,pred_time_test_marginal,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,RandomForestMSE_BAG_L1_FULL,-7.421274e+09,NaN,root_mean_squared_error,0.055053,0.043004,0.557643,0.055053,0.043004,0.557643,1,True,13
1,RandomForestMSE_BAG_L1,-7.421274e+09,-3.221726e+09,root_mean_squared_error,0.057033,0.043004,0.557643,0.057033,0.043004,0.557643,1,True,3
2,ExtraTreesMSE_BAG_L1,-7.428290e+09,-3.271058e+09,root_mean_squared_error,0.042032,0.045742,0.343870,0.042032,0.045742,0.343870,1,True,5
3,ExtraTreesMSE_BAG_L1_FULL,-7.428290e+09,NaN,root_mean_squared_error,0.063544,0.045742,0.343870,0.063544,0.045742,0.343870,1,True,15
4,WeightedEnsemble_L2_FULL,-7.722535e+09,NaN,root_mean_squared_error,0.080053,NaN,27.672735,0.003000,NaN,0.005999,2,True,20
5,XGBoost_BAG_L1_FULL,-8.087801e+09,NaN,root_mean_squared_error,0.007999,NaN,0.133164,0.007999,NaN,0.133164,1,True,17
6,CatBoost_BAG_L1_FULL,-8.579163e+09,NaN,root_mean_squared_error,0.005999,NaN,24.509723,0.005999,NaN,24.509723,1,True,14
7,NeuralNetTorch_BAG_L1_FULL,-8.598606e+09,NaN,root_mean_squared_error,0.008001,NaN,2.466206,0.008001,NaN,2.466206,1,True,18
8,NeuralNetFastAI_BAG_L1_FULL,-8.614052e+09,NaN,root_mean_squared_error,0.037243,NaN,0.474050,0.037243,NaN,0.474050,1,True,16
9,LightGBM_BAG_L1_FULL,-1.112604e+10,NaN,root_mean_squared_error,0.031004,NaN,0.265540,0.031004,NaN,0.265540,1,True,12
10,LightGBMLarge_BAG_L1_FULL,-1.136607e+10,NaN,root_mean_squared_error,0.028510,NaN,0.212734,0.028510,NaN,0.212734,1,True,19
11,LightGBMXT_BAG_L1_FULL,-1.213573e+10,NaN,root_mean_squared_error,0.026505,NaN,0.466976,0.026505,NaN,0.466976,1,True,11
12,WeightedEnsemble_L2,NaN,-2.980625e+09,root_mean_squared_error,NaN,0.131357,173.797436,NaN,0.000000,0.005999,2,False,10
13,XGBoost_BAG_L1,NaN,-3.116125e+09,root_mean_squared_error,NaN,0.031991,1.665522,NaN,0.031991,1.665522,1,False,7
14,CatBoost_BAG_L1,NaN,-3.572457e+09,root_mean_squared_error,NaN,0.015005,161.045488,NaN,0.015005,161.045488,1,False,4
15,NeuralNetFastAI_BAG_L1,NaN,-4.292749e+09,root_mean_squared_error,NaN,0.072011,7.498832,NaN,0.072011,7.498832,1,False,6
16,NeuralNetTorch_BAG_L1,NaN,-4.689785e+09,root_mean_squared_error,NaN,0.041358,10.522784,NaN,0.041358,10.522784,1,False,8
17,LightGBM_BAG_L1,NaN,-6.760417e+09,root_mean_squared_error,NaN,0.015518,1.737179,NaN,0.015518,1.737179,1,False,2
18,LightGBMLarge_BAG_L1,NaN,-7.310346e+09,root_mean_squared_error,NaN,0.014519,1.410837,NaN,0.014519,1.410837,1,False,9
19,LightGBMXT_BAG_L1,NaN,-7.511734e+09,root_mean_squared_error,NaN,0.013999,0.464264,NaN,0.013999,0.464264,1,False,1

In [9]:
predictor.predict(test_data)

7      4.294946e+09
8      4.403822e+09
16     5.713501e+09
17     5.868390e+09
25     2.381346e+10
26     2.375378e+10
34     9.607648e+09
35     9.821832e+09
43     7.862944e+09
44     8.141699e+09
52     1.504830e+10
53     1.519627e+10
61     6.094908e+09
62     6.342513e+09
70     4.701615e+09
71     5.026607e+09
79     6.364384e+09
80     6.683910e+09
88     3.822315e+09
89     3.983748e+09
97     3.510669e+09
98     3.694706e+09
106    3.684732e+09
107    3.812152e+09
115    2.114438e+10
116    2.138064e+10
124    1.315743e+10
125    1.340286e+10
133    1.893995e+10
134    1.901410e+10
Name: value, dtype: float32